declare module '*.jpg';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.png';
declare module '*.svg';
declare module '*.gif';
declare module '*.gif.mp4';
declare module '*.mp4';
declare module '*.mjs'
declare module '*.js'
declare module '*.webp'
declare module 'react-slick'
declare module "*.module.css";
declare module "react-router-hash-link"
declare module "react-image-mapper"
declare module "swiper/react"
declare module "swiper"
declare module "@solana/wallet-adapter-react"
declare module "@solana/wallet-adapter-react-ui"
declare module "@solana/wallet-adapter-base"
declare module "@solana/web3.js"
declare module "firebase/database"
declare module "@solana/wallet-adapter-base"
declare module "@solana/wallet-adapter-base"
declare module "@reduxjs/toolkit/query/react"
declare module "@solana/spl-token"
declare module 'react-copy-to-clipboard'
declare module "tweetnacl-util"
declare module "tweetnacl"
declare module "axios"